package controllers.enums;

public enum Endpoint {
	MEDIAS,
	MEDIAS_COUNT,
	MEDIAS_RATINGS,
	MEDIAS_VIEWS,
	MEDIAS_MEDIAID,
	MEDIAS_URLS_MEDIAFILEID,
	MEDIAS_MEDIAID_RATING,
	MEDIAS_MEDIAID_THUMBS,
	MEDIAS_MEDIAID_VIEWS,
	MEDIAS_VIEWS_MEDIAFILEID,
	MEDIAS_MEDIAID_RELATED,
	MEDIAS_URLS_MEDIAID_OUTPUTNAME,
	MEDIAS_MEDIAID_VIEWS_OUTPUTNAME,
	CHANNELS,
	CHANNELS_COUNT,
	CHANNELS_CHANNELID,
	OUTPUTS,
	OUTPUTS_COUNT,
	REPORT_DETAIL_TRAFFIC,
	REPORT_DETAIL_MEDIAS,
	REPORT_DETAIL_VIEWS,
	REPORT_DETAIL_STORAGE;
}