package controllers.enums;

public enum Endpoint {
	MEDIAS,
	MEDIAS_COUNT,
	MEDIAS_RATINGS,
	MEDIAS_VIEWS,
	MEDIAS_MEDIAID,
	MEDIAS_URLS_MEDIAFILEID,
	MEDIAS_MEDIAID_RATING,
	MEDIAS_MEDIAID_VIEWS,
	CHANNELS;
}
